
channels:
- conda-forge
dependencies:
- python=3.7
- pip=21.3.1
- py-xgboost-gpu
- pip:
  - h5py<=2.10.0
  - azureml-defaults
  - tensorflow-gpu==2.0.0
  - keras<=2.3.1
  - matplotlib
  - protobuf==3.20.1
  - stochastic
  - diff_classifier
  - scikit-learn
  - polars
  - mrmr-selection
  - mlflow
  - azureml-mlflow
